In [41]:
from __future__ import print_function
import torch
import numpy as np

In [2]:
x = torch.empty(5,3) #unititalized
print(x)

tensor(1.00000e-19 *
       [[ 0.0000,  1.0842,  0.0000],
        [ 1.0842,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  1.0842,  0.0000]])


In [20]:
x = torch.rand(5,3) #random
print(x)

tensor([[ 0.1897,  0.4886,  0.0064],
        [ 0.7217,  0.9045,  0.3936],
        [ 0.1791,  0.3909,  0.4065],
        [ 0.1704,  0.4107,  0.3348],
        [ 0.1504,  0.0869,  0.9052]])


In [6]:
x = torch.zeros(5,3, dtype=torch.long) #torch.long = long datatype
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [17]:
x = torch.tensor([5.3, 3])
print(x)

tensor([ 5.3000,  3.0000])


In [14]:
x = torch.ones(5,3)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [19]:
x = x.new_ones(5,3)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [23]:
y = torch.rand(5,3)
print(y)

tensor([[ 0.7916,  0.1553,  0.9881],
        [ 0.2019,  0.0901,  0.8665],
        [ 0.6681,  0.5931,  0.9601],
        [ 0.2351,  0.8086,  0.8808],
        [ 0.1138,  0.3276,  0.3167]])


In [24]:
print(x+y) # addition syntax1

tensor([[ 0.9813,  0.6439,  0.9945],
        [ 0.9236,  0.9946,  1.2601],
        [ 0.8472,  0.9840,  1.3666],
        [ 0.4055,  1.2193,  1.2156],
        [ 0.2642,  0.4145,  1.2219]])


In [25]:
print(torch.add(x,y)) # addition syntax2

tensor([[ 0.9813,  0.6439,  0.9945],
        [ 0.9236,  0.9946,  1.2601],
        [ 0.8472,  0.9840,  1.3666],
        [ 0.4055,  1.2193,  1.2156],
        [ 0.2642,  0.4145,  1.2219]])


In [26]:
x.add_(y) #in place
print(x)

tensor([[ 0.9813,  0.6439,  0.9945],
        [ 0.9236,  0.9946,  1.2601],
        [ 0.8472,  0.9840,  1.3666],
        [ 0.4055,  1.2193,  1.2156],
        [ 0.2642,  0.4145,  1.2219]])


In [34]:
print(x[:,1])
z = x[:,1]
print(z.size())

tensor([ 0.6439,  0.9946,  0.9840,  1.2193,  0.4145])
torch.Size([5])


In [28]:
print(x[2,:])

tensor([ 0.8472,  0.9840,  1.3666])


In [39]:
p = x[2,2]
print(p.item()) # convert one element tensors to numeric

1.3665764331817627


In [40]:
print(x)

tensor([[ 0.9813,  0.6439,  0.9945],
        [ 0.9236,  0.9946,  1.2601],
        [ 0.8472,  0.9840,  1.3666],
        [ 0.4055,  1.2193,  1.2156],
        [ 0.2642,  0.4145,  1.2219]])


In [46]:
a = x.numpy()

In [47]:
print(a)

[[0.981289   0.64387035 0.99452186]
 [0.9235815  0.9945537  1.260104  ]
 [0.8472345  0.9839688  1.3665764 ]
 [0.40554816 1.2193027  1.2156062 ]
 [0.2641827  0.41454935 1.2218981 ]]


In [50]:
x.add_(1) # adding 1 to all elements in place

tensor([[ 1.9813,  1.6439,  1.9945],
        [ 1.9236,  1.9946,  2.2601],
        [ 1.8472,  1.9840,  2.3666],
        [ 1.4055,  2.2193,  2.2156],
        [ 1.2642,  1.4145,  2.2219]])

In [51]:
print(a) #affects numpy array too

[[1.981289  1.6438704 1.9945219]
 [1.9235815 1.9945537 2.260104 ]
 [1.8472345 1.9839687 2.3665764]
 [1.4055481 2.2193027 2.2156062]
 [1.2641827 1.4145494 2.221898 ]]
