In [3]:
from __future__ import print_function
import torch
print(torch.__version__)

0.4.0


In [4]:
a = torch.Tensor([26])

In [5]:
print(type(a))

<class 'torch.Tensor'>


In [6]:
print(a.shape)

torch.Size([1])


In [7]:
t = torch.Tensor(5,3)

In [8]:
print(type(t))

<class 'torch.Tensor'>


In [9]:
print(t.shape)

torch.Size([5, 3])


In [10]:
print(t)

tensor([[ 0.0000,  2.0000,  0.0000],
        [ 2.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [11]:
p = torch.Tensor(4,4)

In [12]:
q = torch.Tensor(4,4)

In [13]:
ones = torch.ones(4,4)

In [14]:
print(p,q,ones)

tensor([[ 0.0000e+00,  2.0000e+00, -3.3496e+11,  2.0005e+00],
        [ 8.3045e-14,  4.5801e-41,  8.3413e-14,  4.5801e-41],
        [ 8.3414e-14,  4.5801e-41,  0.0000e+00,  4.2039e-45],
        [ 0.0000e+00,  0.0000e+00, -3.2792e+11,  3.7020e-40]]) tensor([[ 0.0000,  2.0000,  0.0000,  2.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  2.0000,  0.0000,  2.0000]]) tensor([[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]])


In [15]:
print(p+q)

tensor([[ 0.0000e+00,  4.0000e+00, -3.3496e+11,  4.0005e+00],
        [ 8.3045e-14,  4.5801e-41,  8.3413e-14,  4.5801e-41],
        [ 8.3414e-14,  4.5801e-41,  0.0000e+00,  4.2039e-45],
        [ 0.0000e+00,  2.0000e+00, -3.2792e+11,  2.0000e+00]])


In [16]:
print(p-q)

tensor([[ 0.0000e+00,  0.0000e+00, -3.3496e+11,  4.8685e-04],
        [ 8.3045e-14,  4.5801e-41,  8.3413e-14,  4.5801e-41],
        [ 8.3414e-14,  4.5801e-41,  0.0000e+00,  4.2039e-45],
        [ 0.0000e+00, -2.0000e+00, -3.2792e+11, -2.0000e+00]])


In [17]:
print(p-ones)

tensor([[-1.0000e+00,  1.0000e+00, -3.3496e+11,  1.0005e+00],
        [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00],
        [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00],
        [-1.0000e+00, -1.0000e+00, -3.2792e+11, -1.0000e+00]])


In [18]:
print(p*q)

tensor([[ 0.0000,  4.0000, -0.0000,  4.0010],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.0000,  0.0000]])


In [19]:
print(p*ones)

tensor([[ 0.0000e+00,  2.0000e+00, -3.3496e+11,  2.0005e+00],
        [ 8.3045e-14,  4.5801e-41,  8.3413e-14,  4.5801e-41],
        [ 8.3414e-14,  4.5801e-41,  0.0000e+00,  4.2039e-45],
        [ 0.0000e+00,  0.0000e+00, -3.2792e+11,  3.7020e-40]])


In [20]:
print(q/ones)

tensor([[ 0.0000,  2.0000,  0.0000,  2.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  2.0000,  0.0000,  2.0000]])


In [21]:
print(p/q)

tensor([[        nan,  1.0000e+00,        -inf,  1.0002e+00],
        [ 8.4661e+30,         inf,         inf,         inf],
        [        inf,         inf,         nan,         inf],
        [        nan,  0.0000e+00,        -inf,  1.8510e-40]])


In [22]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000,  2.0000,  0.0000],
        [ 2.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [23]:
result=torch.Tensor(4,4)
torch.add(p,q,out=result)
print(result)

tensor([[ 0.0000e+00,  4.0000e+00, -3.3496e+11,  4.0005e+00],
        [ 8.3045e-14,  4.5801e-41,  8.3413e-14,  4.5801e-41],
        [ 8.3414e-14,  4.5801e-41,  0.0000e+00,  4.2039e-45],
        [ 0.0000e+00,  2.0000e+00, -3.2792e+11,  2.0000e+00]])


In [24]:
#add in place
q.add_(p)
print(q)

tensor([[ 0.0000e+00,  4.0000e+00, -3.3496e+11,  4.0005e+00],
        [ 8.3045e-14,  4.5801e-41,  8.3413e-14,  4.5801e-41],
        [ 8.3414e-14,  4.5801e-41,  0.0000e+00,  4.2039e-45],
        [ 0.0000e+00,  2.0000e+00, -3.2792e+11,  2.0000e+00]])


In [25]:
q[:,0]

tensor(1.00000e-14 *
       [ 0.0000,  8.3045,  8.3414,  0.0000])

In [26]:
print(q.view(16)) # resize tensor

tensor([ 0.0000e+00,  4.0000e+00, -3.3496e+11,  4.0005e+00,  8.3045e-14,
         4.5801e-41,  8.3413e-14,  4.5801e-41,  8.3414e-14,  4.5801e-41,
         0.0000e+00,  4.2039e-45,  0.0000e+00,  2.0000e+00, -3.2792e+11,
         2.0000e+00])
